import {
  DatabaseGlyph,
  CacheGlyph,
  QueueGlyph,
  FilestoreGlyph,
  DatalakeGlyph,
  ServiceGlyph,
  ComputeGlyph,
  ContainerGlyph,
  FunctionGlyph,
  ModelGlyph,
  GatewayGlyph,
  NetworkGlyph,
  CdnGlyph,
  LoadbalancerGlyph,
  SecurityGlyph,
  IdentityGlyph,
  FirewallGlyph,
  UserGlyph,
  TeamGlyph,
  AgentGlyph,
  EventGlyph,
  ChannelGlyph,
  SignalGlyph,
  DocumentGlyph,
  MoneyGlyph,
  TimeGlyph,
  DecisionGlyph,
  MetricGlyph,
  AnchorGlyph,
  TargetGlyph
} from './index.jsx';

export const GLYPH_REGISTRY = {
  database: DatabaseGlyph,
  cache: CacheGlyph,
  queue: QueueGlyph,
  filestore: FilestoreGlyph,
  datalake: DatalakeGlyph,
  service: ServiceGlyph,
  compute: ComputeGlyph,
  container: ContainerGlyph,
  function: FunctionGlyph,
  model: ModelGlyph,
  gateway: GatewayGlyph,
  network: NetworkGlyph,
  cdn: CdnGlyph,
  loadbalancer: LoadbalancerGlyph,
  security: SecurityGlyph,
  identity: IdentityGlyph,
  firewall: FirewallGlyph,
  user: UserGlyph,
  team: TeamGlyph,
  agent: AgentGlyph,
  event: EventGlyph,
  channel: ChannelGlyph,
  signal: SignalGlyph,
  document: DocumentGlyph,
  money: MoneyGlyph,
  time: TimeGlyph,
  decision: DecisionGlyph,
  metric: MetricGlyph,
  anchor: AnchorGlyph,
  target: TargetGlyph
};
